# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_KategoriView(object):
    def setupUi(self, KategoriView):
        KategoriView.setObjectName("KategoriView")
        KategoriView.resize(388, 593)
        self.centralwidget = QtWidgets.QWidget(KategoriView)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditNmKat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNmKat.setGeometry(QtCore.QRect(150, 80, 181, 20))
        self.lineEditNmKat.setObjectName("lineEditNmKat")
        self.pushButtonInsert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonInsert.setGeometry(QtCore.QRect(30, 160, 321, 31))
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(30, 210, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditID.setGeometry(QtCore.QRect(150, 20, 181, 20))
        self.lineEditID.setObjectName("lineEditID")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 240, 361, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoad.setGeometry(QtCore.QRect(30, 520, 321, 31))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        KategoriView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KategoriView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 388, 21))
        self.menubar.setObjectName("menubar")
        KategoriView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KategoriView)
        self.statusbar.setObjectName("statusbar")
        KategoriView.setStatusBar(self.statusbar)

        self.pushButtonInsert.clicked.connect(self.insertkategori)
        self.pushButtonLoad.clicked.connect(self.loadkategori)

        self.retranslateUi(KategoriView)
        QtCore.QMetaObject.connectSlotsByName(KategoriView)
        
        
    def insertkategori(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan_python"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditID.text()
            namekat = self.lineEditNmKat.text()
            sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
            val = (idkat,namekat)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Kategori Berhasil Disimpan")

            self.lineEditID.setText("")
            self.lineEditNmKat.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Kategori Gagal Disimpan")
            
            
    def loadkategori(self):
        try:
        # Koneksi ke database
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan_python"
        )
            mycursor = mydb.cursor()
        
        # Eksekusi query untuk mengambil semua data dari tabel kategori
            mycursor.execute("SELECT * FROM kategori ORDER BY id ASC")
            result = mycursor.fetchall()

        # Cek apakah ada data
            if not result:
                self.labelResult.setText("Tidak ada data di database!")
                return

        # Set jumlah kolom berdasarkan tabel
            self.tableWidget.setColumnCount(len(result[0]))  # Jumlah kolom sesuai hasil query
            self.tableWidget.setRowCount(len(result))        # Jumlah baris sesuai jumlah data
            self.tableWidget.setHorizontalHeaderLabels(["ID Kategori", "Nama Kategori"])  # Set header tabel

        # Masukkan data ke dalam QTableWidget
            for row_number, row_data in enumerate(result):
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))

        # Tampilkan pesan sukses
            self.labelResult.setText("Data Kategori Berhasil Ditampilkan")
        except mc.Error as err:
        # Tangani error koneksi atau query
            self.labelResult.setText(f"Data Kategori Gagal DiLoad: {err}")
        finally:
        # Tutup koneksi database jika terbuka
            if mydb.is_connected():
                mydb.close()



    def retranslateUi(self, KategoriView):
        _translate = QtCore.QCoreApplication.translate
        KategoriView.setWindowTitle(_translate("KategoriView", "Kategori View"))
        self.pushButtonInsert.setText(_translate("KategoriView", "INSERT"))
        # self.pushButtonEdit.setText(_translate("KategoriView", "EDIT"))
        # self.pushButtonDelete.setText(_translate("KategoriView", "DELETE"))
        self.labelResult.setText(_translate("KategoriView", "TextLabel"))
        self.label.setText(_translate("KategoriView", "ID Kategori"))
        self.label_2.setText(_translate("KategoriView", "Nama Kategori"))
        self.pushButtonLoad.setText(_translate("KategoriView", "LOAD DATA"))
        
   



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KategoriView = QtWidgets.QMainWindow()
    ui = Ui_KategoriView()
    ui.setupUi(KategoriView)
    KategoriView.show()
    sys.exit(app.exec_())
